security:
    providers:
        in_memory: { memory: ~ }
        login_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            form_login:
                login_path: login
                check_path: login
                username_parameter: "login[username]"
                password_parameter: "login[password]"
                provider: login_provider
                default_target_path: profile
            logout:
                path: logout
                target: /

    access_control:
         - { path: ^/profile, roles: ROLE_USER }

    encoders:
        App\Entity\User: bcrypt